# Generated by Django 3.1.1 on 2020-12-28 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='t_subscribe',
            fields=[
                ('subscribeID', models.CharField(max_length=33, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('subscribeDetail', models.CharField(max_length=256)),
                ('resourceClass', models.SmallIntegerField(verbose_name=11)),
                ('resourceURI', models.TextField()),
                ('applicantName', models.CharField(max_length=50)),
                ('applicantOrg', models.CharField(max_length=100)),
                ('beginTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
                ('receiveAddr', models.CharField(max_length=256)),
                ('reportInterval', models.SmallIntegerField(verbose_name=11)),
                ('reason', models.CharField(max_length=256)),
                ('operateType', models.SmallIntegerField(verbose_name=11)),
                ('subscribeStatus', models.SmallIntegerField(verbose_name=11)),
                ('subscribeCancelOrg', models.CharField(max_length=100)),
                ('subscribeCancelPerson', models.CharField(max_length=32)),
                ('cancelTime', models.DateTimeField()),
                ('cancelReason', models.CharField(max_length=64)),
                ('resultImageDeclare', models.CharField(max_length=64)),
                ('resultFeatureDeclare', models.CharField(max_length=10)),
                ('type', models.BooleanField()),
                ('viidSystemID', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='t_viid_system',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name=100)),
                ('userName', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=100)),
                ('deviceId', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('ipAddr', models.CharField(max_length=15)),
                ('ipv6Addr', models.CharField(max_length=15)),
                ('port', models.CharField(max_length=6)),
                ('onlineStatus', models.SmallIntegerField(verbose_name=1)),
                ('count', models.SmallIntegerField(verbose_name=11)),
                ('opTime', models.DateTimeField(null=True)),
                ('receiveAddr', models.CharField(max_length=100)),
                ('subscribeDetail', models.CharField(max_length=10)),
                ('type', models.BooleanField()),
            ],
        ),
    ]
