# Generated by Django 3.1.1 on 2020-12-29 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20201229_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_viid_system',
            name='subscribeDetail',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
